name: Fetch Latest Blog Posts
on:
  watch:
    types: [started]
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every 2 days
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Pull in dev.to posts
        uses: zylele/social-readme@master
        with:
          blog_rss_link: https://zylele.github.io/atom.xml
